text = "hello world"
print(text.capitalize())
print(text.center(20, "-"))
print("test.py".endswith(".py"))
print("banana".find("na"))
print("Python3".isalnum())
print("Hello".isalpha())
print("123".isdigit())
print("hello".islower())
print("   ".isspace())
print("HELLO".isupper())
print("-".join(["a", "b"]))
print("HELLO".lower())
print("   hi".lstrip())
print("I like Java".replace("Java", "Python"))
print("banana".rfind("a"))
print("hello   ".rstrip())
print("a b c".split())
print("hello".startswith("he"))
print("   hi   ".strip())
print("Hello".swapcase())
print("hello world".title())
print("hello".upper())
